= link:https://bitbucket.org/daggerok/hg[akka-kotlin]

This repository just about Mercurial learning...

== hg study

=== config

.config
[source,bash]
----
vim ~/.hgrc
...

[ui]
username = Maksim Kostromin <daggerok@gmail.com>
editor = vim

:wq!
----

.clone
[source,bash]
----
hg clone https://bitbucket.org/daggerok/hg

# basically hg clone $URL [ $optionalDestination ]
----

=== common

.or init if new project
[source,bash]
----
mkdir new-project-repo
cd new-project-repo/
hg init
----

.add some files and commit them
[source,bash]
----
touch my-app my-other-app
hg add .
hg commit -m "Add my-app and my-other-app."

# or you can just use command:
hg commit
# in opened editor add commit message and close editor to commit
----

.check status
[source,bash]
----
touch app-not-for-commit
hg status

# output:
# ? app-not-for-commit
----

.status codes
----
M - modified
A - new
R - has been removed
C - clean (not modified sinse last commit)
! - deleted, but still tracked
? - not tracked
I - ignore
----

.review history from mercurial logs
[source,bash]
----
hg log

# output:
changeset:   9:9e5ea6921876
tag:         tip
user:        Maksim Kostromin <Maksim.Kostromin@jeppesen.com>
date:        Thu Dec 28 02:02:23 2017 +0200
summary:     Add status instructions.
----

.remove files
[source,bash]
----
hg remove .DS_Store
hg status

# output:
R .DS_Store
----

.restore accidently removed files from mercurial history
[source,bash]
----
rm -rf build.gradle
ls
hg revert build.gradle

# revert specific revision of file
hg revert build.gradle -r 10
----

.push
[source,bash]
----
hg push
hg push default
hg push --branch default
hg push ssh://hg@bitbucket.org/daggerok/hg --branch default

# force update existing remote history (don't do that!)
hg push --force
----

.diff
[source,bash]
----
# sinse beginning of the history:
hg diff -r 0

# if previouse rev is 15, the show just latest changes using:
hg diff -r 15
----

.copy
[source,bash]
----
# mercutial traks copies in different way during merge it will correctly propagate
hg copy pom.xml pom.xml-copy

# or hg cp pom.xml pom.xml-copy

hg status
# A pom.xml-copy

# natively remove if file wasn't added
rm -rf pom.xml-copy

hg status
# ! pom.xml-copy

# and finally forget this shit
hg forget pom.xml-copy
----

.rename hg rename == hg copy + hg remove
[source,bash]
----
# mercutial traks copies in different way during merge it will correctly propagate
hg rename pom.xml pom.xml-copy
# or hg mv pom.xml pom.xml-copy

hg status
# A pom.xml-copy
# R pom.xml

hg revert pom.xml
hg forget pom.xml
rm -rf pom.xml-copy
----

=== tag

.tags in mercurial doesn't create any pranch, it's just a nickname of specific revision, so changing to ag is same as changing to specific revision
[source,bash]
----
# list of tags
hg tags
# tip                               21:b7dde8210614

hg tag patch-release-0.0.1

hg log
# output
changeset:   22:cf75af294c33
user:        Maksim Kostromin <Maksim.Kostromin@jeppesen.com>
date:        Thu Dec 28 17:17:46 2017 +0200
summary:     Added tag patch-release-0.0.1 for changeset b7dde8210614

changeset:   21:b7dde8210614
tag:         patch-release-0.0.1
user:        Maksim Kostromin <Maksim.Kostromin@jeppesen.com>
date:        Thu Dec 28 16:54:48 2017 +0200
summary:     Update copy and rename instructions. Add tip instruction.
----

=== update

point of `hg update` command:

. update is using to move in history
. folder `.hg` is real repo, but working directory it's just a snapshot pointing in some time from repo

.update to most recent revision
[source,bash]
----
hg update tip

# or same as
hg update
----

.update very first commit
[source,bash]
----
hg update 0
----

.update and discard untracked files / changes forcevly replace state of working directory from revision. if requested revision is from different branch, then requested revision branch will be switched to requested one. if -C not provided, merge will be applied
[source,bash]
----
hg update -C 123
----

=== branch

in mercurial all branches doing to be a part of repository

.create new brunch and swich to it
[source,bash]
----
hg branch feature

# do some work
hg commit

# switch back to default branch
hg update default
----

.check parents of current revision
[source,bash]
----
hg parents
----

.check heads (changes which has no chldren, like tip revision)
[source,bash]
----
hg heads
----

.merge changes from feature branche into default
[source,bash]
----
hg branch
# output:
default

hg merge feature
----

.resolve merge conflicts
[source,bash]
----
hg merge branch-will-conflict

# next you need edit file and seve it

hg resolve -m edited-filename.txt

hg commit -m "Merged branch-will-conflict."
----

=== share repos

todo...

=== ignore

.ignoring files (like subversion, but unlike git) - mercurial is continuing tracking files, so you dont need add them every time
[source,bash]
----
vim .hgignore
...

syntax: glob

*.log
*.ipr
*.iws
.DS_Store
^.*.iml$

:wq!
----

links:

. link:https://app.pluralsight.com/player?course=meet-mercurial[pluralsight course: meet-mercurial]

== project build

.build run and test
[source,bash]
----
docker-compose down -v; ./mvnw clean package; ./gradlew clean build; docker-compose up --build --force-recreate --remove-orphans

# or

docker-compose down -v;
./mvnw clean package;
./gradlew clean build;
docker-compose up --build --force-recreate --remove-orphans
----

== Default README.md

This README would normally document whatever steps are necessary to get your application up and running.

=== What is this repository for?

. Quick summary
. Version
. link:https://bitbucket.org/tutorials/markdowndemo[Learn Markdown (why?)]

=== How do I get set up?

. Summary of set up
. Configuration
. Dependencies
. Database configuration
. How to run tests
. Deployment instructions

=== Contribution guidelines

. Writing tests
. Code review
. Other guidelines

=== Who do I talk to?

. Repo owner or admin
. Other community or team contact
