= link:https://bitbucket.org/daggerok/hg[akka-kotlin]

This repository just about Mercurial learning...

== hg study

.config
[source,bash]
----
vim ~/.hgrc
...

[ui]
username = Maksim Kostromin <daggerok@gmail.com>
editor = vim

:wq!
----

.clone
[source,bash]
----
hg clone https://bitbucket.org/daggerok/hg
----

.or init if new project
[source,bash]
----
mkdir new-project-repo
cd new-project-repo/
hg init
----

.add some files and commit them
[source,bash]
----
touch my-app my-other-app
hg add .
hg commit -m "Add my-app and my-other-app."

# or you can just use command:
hg commit
# in opened editor add commit message and close editor to commit
----

.check status
[source,bash]
----
touch app-not-for-commit
hg status

# output:
# ? app-not-for-commit
----

.review history from mercurial logs
[source,bash]
----
hg log

# output:
changeset:   9:9e5ea6921876
tag:         tip
user:        Maksim Kostromin <Maksim.Kostromin@jeppesen.com>
date:        Thu Dec 28 02:02:23 2017 +0200
summary:     Add status instructions.
----

.remove files
[source,bash]
----
hg remove .DS_Store
hg status

# output:
R .DS_Store
----

.restore accidently removed files from mercurial history
[source,bash]
----
rm -rf build.gradle
ls
hg revert build.gradle

# revert specific revision of file
hg revert build.gradle -r 10
----

.push
[source,bash]
----
hg push
hg push default
hg push --branch default
hg push ssh://hg@bitbucket.org/daggerok/hg --branch default

# force update existing remote history (don't do that!)
hg push --force
----

.diff
[source,bash]
----
# sinse beginning of the history:
hg diff -r 0

# if previouse rev is 15, the show just latest changes using:
hg diff -r 15
----

.copy
[source,bash]
----
# mercutial traks copies in different way during merge it will correctly propagate
hg copy pom.xml pom.xml-copy

hg status
# output:
A pom.xml-copy

# natively remove if file wasn't added
rm -rf pom.xml-copy

hg status
# output:
! pom.xml-copy

# and finally forget this shit
hg forget pom.xml-copy
----


.ignoring files (like subversion, but unlike git) - mercurial is continuing tracking files, so you dont need add them every time
[source,bash]
----
vim .hgignore
...

syntax: glob

*.log
*.ipr
*.iws
.DS_Store
^.*.iml$

:wq!
----

.status codes
----
M - modified
A - new
R - has been removed
C - clean (not modified sinse last commit)
! - deleted, but still tracked
? - not tracked
I - ignore
----

links:

. link:https://app.pluralsight.com/player?course=meet-mercurial[pluralsight course: meet-mercurial]

== project build

.build run and test
[source,bash]
----
docker-compose down -v; ./mvnw clean package; ./gradlew clean build; docker-compose up --build --force-recreate --remove-orphans

# or

docker-compose down -v;
./mvnw clean package;
./gradlew clean build;
docker-compose up --build --force-recreate --remove-orphans
----

== Default README.md

This README would normally document whatever steps are necessary to get your application up and running.

=== What is this repository for?

. Quick summary
. Version
. link:https://bitbucket.org/tutorials/markdowndemo[Learn Markdown (why?)]

=== How do I get set up?

. Summary of set up
. Configuration
. Dependencies
. Database configuration
. How to run tests
. Deployment instructions

=== Contribution guidelines

. Writing tests
. Code review
. Other guidelines

=== Who do I talk to?

. Repo owner or admin
. Other community or team contact
